# Generated by Django 2.2.5 on 2019-09-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursebook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='courseclass',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursecondition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursecore',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursepercent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursestruct',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursesubject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coursetarget',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='courseweek',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False},
        ),
    ]
